# Generated by Django 4.2.5 on 2023-10-12 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='note',
            new_name='name',
        ),
    ]
